export const studentRows = [
  {
    id: 1,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 2,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 3,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 4,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 5,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 6,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 7,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 8,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 9,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 10,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 11,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 12,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 13,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 14,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
  {
    id: 15,
    firstName: "Hassan",
    lastName: "Saleem",
    userName: "hassansaleem98",
    email: "hassan.saleem@acclivousbyte.com",
    phone: "0307-4053033",
  },
];
